import Head from 'next/head';
import { trpc } from '../utils/trpc';
import { Layout } from '../components/Layout';


const Home = () => {
  // const { data } = trpc.hello.useQuery({ text: 'client' });
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout />
      </main>
    </>
  );
};

export default Home;